/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
1200 fits failed out of a total of 1200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1200 fits failed with the following error:
Traceback (most recent call last):
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/skorch/classifier.py", line 141, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/skorch/net.py", line 1228, in fit
    self.initialize()
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/skorch/net.py", line 820, in initialize
    self._validate_params()
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/skorch/net.py", line 1961, in _validate_params
    raise ValueError(full_msg)
ValueError: __init__() got unexpected argument(s) error_score. Either you made a typo, or you added new arguments in a subclass; if that is the case, the subclass should deal with the new arguments explicitly.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/sklearn/model_selection/_search.py:972: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan]
  category=UserWarning,
/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/sklearn/model_selection/_search.py:972: UserWarning: One or more of the train scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan]
  category=UserWarning,
Dataset name:  ionchannels_membraneproteins
Dataset type:  balanced
Dataset split:  test
Model name:  ProtB
Traceback (most recent call last):
  File "train_classifiers.py", line 251, in <module>
    grid_search.fit(train_dataset, y_train)
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 926, in fit
    self.best_estimator_.fit(X, y, **fit_params)
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/skorch/classifier.py", line 141, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/skorch/net.py", line 1228, in fit
    self.initialize()
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/skorch/net.py", line 820, in initialize
    self._validate_params()
  File "/home/h_ghazik/python_path_gpu/lib/python3.7/site-packages/skorch/net.py", line 1961, in _validate_params
    raise ValueError(full_msg)
ValueError: __init__() got unexpected argument(s) error_score. Either you made a typo, or you added new arguments in a subclass; if that is the case, the subclass should deal with the new arguments explicitly.
